version: "{build}"

os: Visual Studio 2017

shallow_clone: true

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

before_build:
  # - nuget install glew
  # - nuget install glm
  # - nuget install glfw
  - nuget restore
  - cmake --version || true
  - g++ --version || true
  - clang++ --version || true

build_script:
  - bash ./configure
  - cd build
  - make

test: off
