version: "{build}"

os: Visual Studio 2015

clone_folder: c:\projects\Voidstar
shallow_clone: true
clone_depth: 3

configuration: Release
platform:
  - x64
  - x86

before_build:
  - cmake --version || true
  - g++ --version || true
  - clang++ --version || true
  # - nuget install glew
  # - nuget install glm
  # - nuget install glfw
  # - nuget restore
  - cd c:\projects\Voidstar
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..

build:
  # verbosity: minimal
  project: c:\projects\Voidstar\build\voidstar.sln

on_success:
  - appveyor PushArtifact c:\projects\Voidstar\build\voidstar.exe

on_failure:
  - ls -lha c:\projects\Voidstar\build
  # - nuget install glew
