version: "{build}"

os: Visual Studio 2015

clone_folder: c:\projects\Voidstar
shallow_clone: true
clone_depth: 3

configuration: Release
platform:
  - x64
  - x86

install:
  - set root_dir=%cd%
  # - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat amd64
  - set PATH=%PATH%;C:\"Program Files (x86)"\7-zip

  - SET glew_zip="glew-2.0.0.zip"
  - powershell -Command "(New-Object System.Net.WebClient).DownloadString('https://netcologne.dl.sourceforge.net/project/glew/glew/2.0.0/glew-2.0.0.zip') > '%glew_zip%'"
  - 7z x -o"%root_dir%" "%glew_zip%"
  - cd "%root_dir%\glew-2.0.0"
  - cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%root_dir%\glew-2.0.0\glew-bin" ./cmake
  - nmake
  - cmake -P cmake_install.cmake

  # - choco install glfw3

  - cd %root_dir%

before_build:
  - cmake --version || true
  - g++ --version || true
  - clang++ --version || true
  - cd c:\projects\Voidstar
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..

build:
  # verbosity: minimal
  project: c:\projects\Voidstar\build\voidstar.sln

on_success:
  - appveyor PushArtifact c:\projects\Voidstar\build\voidstar.exe

on_failure:
  - ls -lha
