shallow_clone: true

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

os: Visual Studio 2015

before_build:
  - nuget install glew
  - nuget install glm
  - nuget install glfw
  - cmake --version || true
  - g++ --version || true
  - clang++ --version || true

build_script:
  - bash ./configure
  - cd build
  - make
